services:
  - type: web
    name: supertasks-api
    env: ruby
    plan: free
    rootDir: ./super_tasks_backend
    autoDeploy: true
    buildCommand: |
      bundle install
      bundle exec rails db:prepare
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
