services:
  - type: web
    name: super_tasks-api
    env: ruby
    plan: free
    rootDir: . # ← ルートに固定（ここが原因にならないようにする）
    buildCommand: |
      set -e
      ls -la
      cd super_tasks/super_tasks_backend
      ls -la
      bundle install
      bundle exec rails db:prepare
    startCommand: |
      cd super_tasks/super_tasks_backend
      bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        sync: false # 値はGUIで入力（このファイルには書かない）
      - key: RAILS_MASTER_KEY
        sync: false # credentialsを使う場合のみGUIで入力
