name: Bug_report
description: 不具合報告
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes: { label: 事象, placeholder: 何が起きた？再現手順は？ }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: 本来の期待挙動 }
  - type: textarea
    id: env
    attributes: { label: 環境, placeholder: OS/Browser/Version など }
  - type: textarea
    id: logs
    attributes: { label: ログ/スクショ }
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options: ["high", "medium", "low"]
