name: config
description: 設定変更・CI・ライブラリアップデート等
labels: ["chore"]
body:
  - type: input
    id: summary
    attributes: { label: 概要 }
    validations: { required: true }
  - type: textarea
    id: tasks
    attributes:
      label: 作業項目
      value: |
        - [ ] 変更内容
        - [ ] 動作確認
