name: Feature_request
description: 新機能の追加や仕様変更
labels: ["backend"]
body:
  - type: input
    id: summary
    attributes: { label: 概要, placeholder: 何を実現するか？ }
    validations: { required: true }
  - type: textarea
    id: background
    attributes: { label: 背景/目的, placeholder: なぜ必要か？ビジネス/UX視点も }
  - type: textarea
    id: requirements
    attributes:
      label: 受け入れ条件 (Acceptance Criteria)
      value: |
        - [ ] 条件1
        - [ ] 条件2
        - [ ] 条件3
  - type: textarea
    id: tasks
    attributes:
      label: タスク (WBS)
      value: |
        - [ ] 実装
        - [ ] テスト
        - [ ] ドキュメント更新
  - type: dropdown
    id: sp
    attributes:
      label: ストーリーポイント
      options: ["1", "2", "3", "5", "8"]
    validations: { required: true }
  - type: input
    id: branch
    attributes: { label: ブランチ名(案), placeholder: feature/#123-your-topic }
